app/Models/Client.cs
using System.Collections.Generic;

namespace app.Models
{
  public class Client
  {

    public string         Nombre        { get; set; }
    public string         Apellido      { get; set; }
    public string         Edad          { get; set; }
    public string         Nacionalidad  { get; set; }
    public string         Sexo          { get; set; }
    public string         Apodo         { get; set; }
    public string         Telefono      { get; set; }
    public Direccion      Direccion     { get; set; }
    public List<Carrito>  Detail        { get; set; }

  }

  public class Direccion
  {
    public string Calle       { get; set; }
    public string Colonia     { get; set; }
    public string Delegacion { get; set; }
    public string Numero       { get; set; }
    public string Referencias { get; set; }
  }

  public class Carrito
  {
    public string DescripcionProducto {get; set; }
    public double Precio              { get; set; }
    public double Descuento           { get; set; }
    public int    Cantidad            { get; set; }
    public int    CantidadDisponible  { get; set; }
  }

}

app/Models/ErrorViewModel.cs
using System;

namespace app.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

app/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace app.Controllers
{
    public class MenuController : Controller
    {
        public ActionResult Index()
        {
          Console.WriteLine("Index Method del MenuController");
          return View();
        }

    public ActionResult Angular()
    {
      Console.WriteLine("Angular Method del MenuController");
      return View("AngularIndex");
    }

    public ActionResult React()
    {
      Console.WriteLine("React Method del MenuController");
      return View("ReactIndex");
    }

  }
}

app/Controllers/SerrvicesJsonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using app.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace app.Controllers
{
    public class SerrvicesJsonController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


    public JsonResult StoresList()
    {
      //Result
      RootObject res =JsonConvert.DeserializeObject<RootObject>(JsonStores.JsonStringStores);
      return Json(res);
    }


      public JsonResult CheckOut()
        {
          return Json(new Client {
                Nombre        ="Mario",
                Apellido      ="Andrade",
                Edad          ="26",
                Nacionalidad  ="Mexicana",
                Sexo          ="Hombre",
                Apodo         ="Mayin Buu",
                Telefono      ="553269878",
                Direccion     =new Direccion {
                              Calle      ="Jalisco",
                              Colonia    ="Hidalgo",
                              Numero     ="6",
                              Referencias="Es un edificio",
                              Delegacion="Tlalpan"
                },
                Detail        = new List<Carrito> {
                  new Carrito{
                      DescripcionProducto ="Mouse",
                      Precio              =150,
                      Descuento           =0,
                      Cantidad            =1,
                      CantidadDisponible  =100
                  },
                  new Carrito{
                      DescripcionProducto ="Teclado",
                      Precio              =350,
                      Descuento           =50,
                      Cantidad            =1,
                      CantidadDisponible  =100
                  }
                }
          });
        }
  }
}

app/Views/Menu/AngularIndex.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
  ANGULAR QUE PASA
</body>
</html>

app/Views/Menu/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Menu</title>
</head>
<body>
  @Html.ActionLink("React Menu", "React", "Menu") <br />
  @Html.ActionLink("Angular Menu", "Angular", "Menu")<br />
</body>
</html>

app/Views/Menu/ReactIndex.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title></title>
  <script src="https://unpkg.com/react@15.3.2/dist/react.js"></script>
  <script src="https://unpkg.com/react-dom@15.3.2/dist/react-dom.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
  <script src="~/ReactComponents/ContantsReact.js"></script>
  <script src="~/ReactComponents/ButtonClasess.js"></script>
  <script type="text/babel">
    //var Component=React.Component;
    <h1>Hiiiii</h1>;

    class MyButton extends Component
    {
    render(){
    return (
    <button onClick={this.Push}>Push</button>);
    }
    Push()
    {
    console.log('Push Push');
    }
    }
    ReactDOM.render
    (
    <MyButton />,
    document.querySelector("#CustomHello")
    );
    ReactDOM.render
    (
    HtmlCodeButton,
    document.querySelector("#Container")
    );
  </script>

</head>
<body>
  <div id="CustomHello">
  </div>
  <div id="Container">
  </div>
</body>

</html>